### ISSUE TITLE
Pre-filtering to prevent: too much traffic for live tailing

### ISSUE THREAD

**Issue by RaniSputnik** [cloudflare/wrangler#1434]
#### Overview and problem statement

We are seeing exceptions in production that we are struggling to diagnose. We have followed all of [the debugging tips]() here, including wrapping our handler in a try/catch and firing off error logs but I still have no visibility into the errors which suggests to me the exceptions are being thrown outside of the handler. Unfortunately, we don't know how to replicate these errors and we're not seeing them in our non-prod environments.

What I would like to do now is pull logs from production, but when trying to use `wrangler tail` I get the following error.

```
$ npx wrangler tail --env master | grep "exception" > exceptions.txt
🦚  Setting up log streaming from Worker script "master". Using ports 8080 and 8081.
⠲   This may take a few seconds...
Error: ⚠️  Code 10057: workers.api.error.too_much_traffic_for_live_tailing
🕵️  See documentation
```

What I'd like to propose is a couple of improvements:

1. Document whether there is _any_ mitigation option available folks who encounter this issue
2. Provide some way to pre-filter logs before they enter the tail pipe

I think many services would seek to provide a sampled tail when traffic is too high, and this might be a great solution, but only if it removed duplicate log entries. If I lost unique (and valuable) exception logs as a result of sampling then that would be equally frustrating.

I understand this request is probably unreasonably difficult, but as it stands today I don't really have any other options.

#### Basic example

Provide a `--sample` flag to indicate that we're happy to only receive a sample of the logs in the given environment.

```
$ npx wrangler tail --sample
```

**Comment by ashleymichal** [comment]
@RaniSputnik this is a platform level feature request; the work to be done needs to come from the runtime and core api as well as Wrangler, and has not yet been prioritized, but we do have a few ideas around improving the tracing experience in Workers. I'll raise an internal ticket and link this issue. If any work is added to the roadmap I'll be sure to post updates here.

**Comment by bjesus** [comment]
has there been any progress on this? we are currently completely unable to `tail` any of our production workers. Wrangler just shouts `Error: ⚠️  Code 10057: workers.api.error.too_much_traffic_for_live_tailing
🕵️  See documentation`. As much as the emojis are nice, which documentation exactly?

**Comment by ScottHelme** [comment]
I'm hitting this error at present. Was there any documentation I should be looking at or any way to handle this just yet?

**Comment by rorito** [comment]
I've been getting "Error: ⚠️  Code 10057: workers.api.error.too_much_traffic_for_live_tailing" for multiple hours today. We're unable to debug production without log access.

**Comment by dungahk** [comment]
Sorry to comment on a closed and old issue, but can we at least change the code to link to the documentation instead? I actually haven't found anything in the documentation so far mentioning this limitation though.

**Comment by nicwisepub** [comment]
+1 for a resolution to this issue. We cannot debug any of our cloud workers as a result.

**Comment by aaronpeters** [comment]
+1 for a solution for this. Frustrating to not be able to tail the logs on production at the time it's most needed to debug (e.g. huge spike in incoming requests, what is going on??)

**Comment by nicwisepub** [comment]
Thanks for re-opening. I am happy to be test subject for this. We're currently running 3-4k requests per minute through our worker.

**Comment by nilslice** [comment]
We are actively working on a significant improvement to tailing worker logs - we'll update this thread once there is more to share soon.

**Comment by nicovigil1** [comment]
Any updates on this? I can see wrangler was updated about 4 days ago, is there any chance there's a workaround baked in?

**Comment by nilslice** [comment]
@nicovigil1 - we released partial support for filtering tails, and more comprehensive filtering support is coming. Thanks for following up, someone will be sure to ping this thread once it has fully shipped! We'd love to get your feedback on it, especially with high-traffic use cases.

**Comment by nicwisepub** [comment]
@nilslice, any docs on the partial support?

**Comment by nicwisepub** [comment]
@nilslice FYI, after upgrading tail fails silently for me. We're doing 3-4k RPM right now.
`wrangler tail
🦚  Setting up log streaming from Worker script "XXXX". Using ports 8080 and 8081.
This may take a few seconds...`

**Comment by nicwisepub** [comment]
FYI, I am still getting the following error now on 1.19:

`Error: Failed to create tail: ⚠️  Code 10057: workers.api.error.too_much_traffic_for_live_tailing`

**Comment by salarkhan** [comment]
@nilslice love the improvements to `wrangler tail`, much easier than the old way using/configuring `cloudflared`. thanks!

unfortunately, our production traffic is still un-tailable. my expectation is that the RPS displayed in the error message would be lower if i applied a `sampling-rate` flag, but that does not seem to be the case:
```
local:~: wrangler tail --format pretty -e production
Error: Failed to create tail: ⚠️  Code 10057: This script has too much traffic: 106759 invocations per second, which is over the limit of 100.
```
```
local:~: wrangler tail --format pretty --sampling-rate .01 -e production
Error: Failed to create tail: ⚠️  Code 10057: This script has too much traffic: 123268 invocations per second, which is over the limit of 100.
```
i tried adding a number of other flags to bring it further down (including searching for a term that i know is not logged), but to no avail
```
local:~: wrangler tail --format pretty --status error --sampling-rate .01 --search "foobar" -e production
Error: Failed to create tail: ⚠️  Code 10057: This script has too much traffic: 104007 invocations per second, which is over the limit of 100.
```

**Comment by nilslice** [comment]
@salarkhan  - glad to hear it! pinging someone from the team to take a look.

**Comment by niko-fp** [comment]
Any update on this topic? We have the same issue
```bash
wrangler tail --format pretty --status error --sampling-rate .01 --search "foobar" -e production
Error: Failed to create tail: ⚠️  Code 10057: This script has too much traffic: 13051 invocations per second, which is over the limit of 100.
```

**Comment by PSjoe** [comment]
We're also having this issue.  We can't tail any logs from our production workers.   There doesn't seem to be any combination of `sampling-rate` or `status` or anything else that will let us see what's going on.
